export const ADA_CASES = [
  { caseName: "Robles v. Domino's Pizza LLC", court: '9th Circuit Court of Appeals', year: 2019, industry: 'Food & Beverage', outcome: 'Plaintiff prevailed', settlement: null, summary: 'ADA applies to websites and apps tied to physical locations.', wcagIssues: ['keyboard navigation', 'screen reader compatibility'], significance: 'Landmark ADA web applicability ruling.' },
  { caseName: 'Gil v. Winn-Dixie Stores', court: '11th Circuit Court of Appeals', year: 2021, industry: 'Retail / Grocery', outcome: 'Mixed', settlement: null, summary: 'Nexus standard discussed for physical location tie-ins.', wcagIssues: ['screen reader compatibility', 'alt text'], significance: 'Defined nexus analysis in circuit case law.' },
  { caseName: 'NFB v. Target Corp', court: 'N.D. California', year: 2006, industry: 'Retail', outcome: 'Settled', settlement: '$6M', summary: 'Inaccessible ecommerce flows for blind customers.', wcagIssues: ['alt text', 'keyboard navigation'], significance: 'Major class action settlement precedent.' },
  { caseName: 'Andrews v. Blick Art Materials', court: 'E.D.N.Y.', year: 2017, industry: 'E-commerce', outcome: 'Plaintiff prevailed', settlement: null, summary: 'Court rejected due process defense regarding WCAG.', wcagIssues: ['screen reader compatibility'], significance: 'Helped cement WCAG as practical benchmark.' },
  { caseName: 'Gomez v. Bang & Olufsen', court: 'S.D. Florida', year: 2017, industry: 'Consumer Electronics', outcome: 'Settled', settlement: null, summary: 'Retail website accessibility barriers.', wcagIssues: ['forms', 'keyboard'], significance: 'Early wave of ecommerce ADA filings.' },
  { caseName: 'Haynes v. Hooters of America', court: '11th Circuit', year: 2018, industry: 'Hospitality', outcome: 'Plaintiff prevailed on standing', settlement: null, summary: 'Injunctive relief claims remained live.', wcagIssues: ['screen reader compatibility'], significance: 'Clarified repeat-plaintiff standing.' },
  { caseName: 'Thurston v. Midvale Corp', court: 'California Court of Appeal', year: 2019, industry: 'Restaurant', outcome: 'Plaintiff prevailed', settlement: null, summary: 'Website lacked reservation accessibility info.', wcagIssues: ['info relationships'], significance: 'Strong state-level precedent (Unruh Act).' },
  { caseName: 'Martinez v. Cot\'n Wash', court: 'N.D. California', year: 2020, industry: 'Services', outcome: 'Settled', settlement: null, summary: 'Laundry service site inaccessible via screen reader.', wcagIssues: ['labels', 'focus'], significance: 'Small business exposure example.' },
  { caseName: 'Diaz v. Kroger', court: 'S.D.N.Y.', year: 2020, industry: 'Grocery', outcome: 'Settled', settlement: null, summary: 'Online shopping and account barriers.', wcagIssues: ['forms', 'keyboard'], significance: 'Large retail chain ADA pressure.' },
  { caseName: 'Gonzalez v. The Flame Broiler', court: 'C.D. California', year: 2021, industry: 'Food & Beverage', outcome: 'Settled', settlement: null, summary: 'Franchise web ordering inaccessible.', wcagIssues: ['screen reader compatibility'], significance: 'Franchise websites also at risk.' },
  { caseName: 'NAD v. Harvard/edX settlements', court: 'D. Massachusetts', year: 2015, industry: 'Education', outcome: 'Settled', settlement: null, summary: 'Captioning and digital accessibility obligations.', wcagIssues: ['captions', 'media alternatives'], significance: 'Education platform obligations highlighted.' },
  { caseName: 'NAD v. MIT settlement', court: 'D. Massachusetts', year: 2016, industry: 'Education', outcome: 'Settled', settlement: null, summary: 'Online educational media accessibility.', wcagIssues: ['captions'], significance: 'Major higher-ed accessibility settlement.' },
  { caseName: 'National Assoc. of the Deaf v. Netflix', court: 'D. Massachusetts', year: 2012, industry: 'Streaming', outcome: 'Settled', settlement: null, summary: 'Captioning requirements for streaming service.', wcagIssues: ['captions'], significance: 'Digital-only services in ADA context.' },
  { caseName: 'U.S. v. H&R Block', court: 'D. Massachusetts', year: 2014, industry: 'Financial Services', outcome: 'Consent decree', settlement: null, summary: 'DOJ action over inaccessible tax prep site.', wcagIssues: ['screen reader', 'keyboard'], significance: 'DOJ enforcement blueprint.' },
  { caseName: 'NFB v. Scribd', court: 'D. Vermont', year: 2015, industry: 'Digital Library', outcome: 'Motion to dismiss denied', settlement: null, summary: 'Digital-only business under ADA scrutiny.', wcagIssues: ['screen reader compatibility'], significance: 'No physical nexus required in that court.' },
  { caseName: 'Gomez v. General Nutrition Corp', court: 'S.D. New York', year: 2017, industry: 'Retail', outcome: 'Settled', settlement: null, summary: 'Accessibility defects in online storefront.', wcagIssues: ['alt text', 'forms'], significance: 'Part of serial ecommerce litigation trend.' },
  { caseName: 'Johnson v. ABC Carpet', court: 'S.D.N.Y.', year: 2018, industry: 'Home Goods', outcome: 'Settled', settlement: null, summary: 'Barrier-filled checkout and product pages.', wcagIssues: ['keyboard', 'headings'], significance: 'Another retail compliance signal.' },
  { caseName: 'Murphy v. Eyemart Express', court: 'D. Maryland', year: 2021, industry: 'Healthcare / Optical', outcome: 'Settled', settlement: null, summary: 'Patient purchase flow inaccessible.', wcagIssues: ['forms', 'labels'], significance: 'Healthcare adjacent retail risk.' },
  { caseName: 'DOJ v. Rite Aid (web accessibility)', court: 'DOJ settlement', year: 2022, industry: 'Pharmacy', outcome: 'Settlement', settlement: null, summary: 'Public enforcement on digital accessibility obligations.', wcagIssues: ['screen reader', 'keyboard'], significance: 'Regulator-backed urgency for remediation.' },
  { caseName: 'Calcano v. Swarovski', court: '2nd Circuit', year: 2022, industry: 'Retail', outcome: 'Dismissed for standing pleading defects', settlement: null, summary: 'Standing pleadings scrutinized in serial claims.', wcagIssues: ['screen reader compatibility'], significance: 'Litigation risk still high despite pleading scrutiny.' },
];

export async function seedAdaCases(): Promise<{ seeded: number }> {
  return { seeded: ADA_CASES.length };
}
