import { knowledgePlatformFunctions } from '@/inngest/knowledge-platform';

export const inngestFunctions = [
  'preScanLead',
  'processDeployGate',
  'sendNotification',
  'generateDailyBriefing',
  'generateLegalAssessment',
  'seedAdaCases',
  'processDeployGateV2',
  'generateIntelligenceFeedItem',
  'certificationRenewalCheck',
  'sendRenewalReminder',
  'procurementIntelligenceScan',
  'generateRfpResponseKit',
  'notifyDevelopersNewJob',
  'processMarketplacePayment',
  'copilotEmergencyMode',
  'copilotWeeklyBrief',
  'processScanQueue',
  'killStuckScansCron',
  'processWebhookRetries',
  'dailyBackupExport',
  'pdfGenerationWorker',
  ...knowledgePlatformFunctions.map((fn) => fn.id),
] as const;
