CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_scans_org_id ON scans(org_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_scans_site_id ON scans(site_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_scans_created_at ON scans(created_at DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_scans_status ON scans(status) WHERE status != 'complete';
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_scans_org_created ON scans(org_id, created_at DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_violations_scan_id ON violations(scan_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_violations_impact ON violations(impact);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_violations_status ON violations(status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_violations_rule ON violations(rule_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_leads_assigned ON leads(assigned_to);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_leads_risk ON leads(compliance_risk);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_leads_industry ON leads(industry);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_leads_domain ON leads(domain);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_feed_org_created ON intelligence_feed(org_id, created_at DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_feed_dismissed ON intelligence_feed(dismissed) WHERE dismissed = false;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cert_token ON certifications(certification_token);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cert_org ON certifications(org_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cert_status ON certifications(status) WHERE status = 'active';
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_api_keys_hash ON api_keys(hash);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_org_time ON audit_log(org_id, timestamp DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_action ON audit_log(action);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_leads_fts ON leads USING gin(to_tsvector('english', business_name || ' ' || coalesce(website_url,'') || ' ' || coalesce(contact_name,'')));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_scans_url_fts ON scans USING gin(to_tsvector('english', url));
ANALYZE scans;
ANALYZE violations;
ANALYZE leads;
ANALYZE intelligence_feed;
